package com.example.flikky.util

import java.security.SecureRandom
import java.util.Base64
import java.util.concurrent.atomic.AtomicLong

object IdGen {
    private val random = SecureRandom()
    private val messageCounter = AtomicLong(0L)

    fun newPin(): String {
        val n = random.nextInt(1_000_000)
        return n.toString().padStart(6, '0')
    }

    fun newToken(): String {
        val bytes = ByteArray(16)
        random.nextBytes(bytes)
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
    }

    fun newMessageId(): Long = messageCounter.incrementAndGet()

    /**
     * Raise the message-id counter so the next [newMessageId] returns a value
     * strictly greater than [persistedMax].
     *
     * `messageCounter` is process-volatile (starts at 0 every launch). Without
     * this, a cold restart with existing history would mint ids 1,2,3… that
     * collide with already-persisted `messages.id` PRIMARY KEYs — the insert
     * throws SQLiteConstraintException, the message never persists, and the
     * session is rolled back as "empty" on stop (silent history loss, a latent
     * bug since v1.0 where MessageEntity.id is non-autogenerated).
     *
     * Seed once at app start from `SELECT MAX(id) FROM messages`. Monotonic:
     * a smaller (e.g. stale) seed never rewinds the counter.
     */
    fun seedMessageCounter(persistedMax: Long) {
        messageCounter.updateAndGet { current -> maxOf(current, persistedMax) }
    }
}
