// AUTO-GENERATED from Material Theme Builder export "material-theme5-ananBlue". DO NOT EDIT BY HAND.
// 色值逐字搬自 MTB 导出（未自造）；重生成见 scripts/gen_schemes.mjs + Phase 3 audit。
package com.example.flikky.ui.theme.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** AnanBlue 主题的 6 套 MD3 ColorScheme（light/dark × 标准/中/高对比度）。 */
internal object AnanBlueScheme : ThemeScheme {
    private val primaryLight = Color(0xFF33618D)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFD0E4FF)
    private val onPrimaryContainerLight = Color(0xFF144974)
    private val secondaryLight = Color(0xFF526070)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFD6E4F7)
    private val onSecondaryContainerLight = Color(0xFF3B4857)
    private val tertiaryLight = Color(0xFF695779)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFF0DBFF)
    private val onTertiaryContainerLight = Color(0xFF514060)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFF8F9FF)
    private val onBackgroundLight = Color(0xFF191C20)
    private val surfaceLight = Color(0xFFF8F9FF)
    private val onSurfaceLight = Color(0xFF191C20)
    private val surfaceVariantLight = Color(0xFFDEE3EB)
    private val onSurfaceVariantLight = Color(0xFF42474E)
    private val outlineLight = Color(0xFF73777F)
    private val outlineVariantLight = Color(0xFFC2C7CF)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF2D3135)
    private val inverseOnSurfaceLight = Color(0xFFEFF1F6)
    private val inversePrimaryLight = Color(0xFF9ECAFC)
    private val surfaceDimLight = Color(0xFFD8DAE0)
    private val surfaceBrightLight = Color(0xFFF8F9FF)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFF2F3F9)
    private val surfaceContainerLight = Color(0xFFECEEF4)
    private val surfaceContainerHighLight = Color(0xFFE6E8EE)
    private val surfaceContainerHighestLight = Color(0xFFE0E2E8)
    private val primaryLightMediumContrast = Color(0xFF00385F)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF43709D)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF2A3746)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF616E7F)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF402F4F)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF796688)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFF8F9FF)
    private val onBackgroundLightMediumContrast = Color(0xFF191C20)
    private val surfaceLightMediumContrast = Color(0xFFF8F9FF)
    private val onSurfaceLightMediumContrast = Color(0xFF0E1115)
    private val surfaceVariantLightMediumContrast = Color(0xFFDEE3EB)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF32373D)
    private val outlineLightMediumContrast = Color(0xFF4E535A)
    private val outlineVariantLightMediumContrast = Color(0xFF696D75)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF2D3135)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF1F6)
    private val inversePrimaryLightMediumContrast = Color(0xFF9ECAFC)
    private val surfaceDimLightMediumContrast = Color(0xFFC4C6CC)
    private val surfaceBrightLightMediumContrast = Color(0xFFF8F9FF)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFF2F3F9)
    private val surfaceContainerLightMediumContrast = Color(0xFFE6E8EE)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFDBDDE3)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFCFD1D7)
    private val primaryLightHighContrast = Color(0xFF002E4F)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF184C76)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF202D3C)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF3D4A5A)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF352544)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF534263)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFF8F9FF)
    private val onBackgroundLightHighContrast = Color(0xFF191C20)
    private val surfaceLightHighContrast = Color(0xFFF8F9FF)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFDEE3EB)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF282D33)
    private val outlineVariantLightHighContrast = Color(0xFF454A50)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF2D3135)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFF9ECAFC)
    private val surfaceDimLightHighContrast = Color(0xFFB6B9BE)
    private val surfaceBrightLightHighContrast = Color(0xFFF8F9FF)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFEFF1F6)
    private val surfaceContainerLightHighContrast = Color(0xFFE0E2E8)
    private val surfaceContainerHighLightHighContrast = Color(0xFFD2D4DA)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFC4C6CC)
    private val primaryDark = Color(0xFF9ECAFC)
    private val onPrimaryDark = Color(0xFF003356)
    private val primaryContainerDark = Color(0xFF144974)
    private val onPrimaryContainerDark = Color(0xFFD0E4FF)
    private val secondaryDark = Color(0xFFBAC8DB)
    private val onSecondaryDark = Color(0xFF243240)
    private val secondaryContainerDark = Color(0xFF3B4857)
    private val onSecondaryContainerDark = Color(0xFFD6E4F7)
    private val tertiaryDark = Color(0xFFD5BEE5)
    private val onTertiaryDark = Color(0xFF3A2A48)
    private val tertiaryContainerDark = Color(0xFF514060)
    private val onTertiaryContainerDark = Color(0xFFF0DBFF)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF101418)
    private val onBackgroundDark = Color(0xFFE0E2E8)
    private val surfaceDark = Color(0xFF101418)
    private val onSurfaceDark = Color(0xFFE0E2E8)
    private val surfaceVariantDark = Color(0xFF42474E)
    private val onSurfaceVariantDark = Color(0xFFC2C7CF)
    private val outlineDark = Color(0xFF8C9199)
    private val outlineVariantDark = Color(0xFF42474E)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFE0E2E8)
    private val inverseOnSurfaceDark = Color(0xFF2D3135)
    private val inversePrimaryDark = Color(0xFF33618D)
    private val surfaceDimDark = Color(0xFF101418)
    private val surfaceBrightDark = Color(0xFF36393E)
    private val surfaceContainerLowestDark = Color(0xFF0B0E12)
    private val surfaceContainerLowDark = Color(0xFF191C20)
    private val surfaceContainerDark = Color(0xFF1D2024)
    private val surfaceContainerHighDark = Color(0xFF272A2F)
    private val surfaceContainerHighestDark = Color(0xFF32353A)
    private val primaryDarkMediumContrast = Color(0xFFC4DFFF)
    private val onPrimaryDarkMediumContrast = Color(0xFF002744)
    private val primaryContainerDarkMediumContrast = Color(0xFF6894C3)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFD0DEF1)
    private val onSecondaryDarkMediumContrast = Color(0xFF192735)
    private val secondaryContainerDarkMediumContrast = Color(0xFF8492A3)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFEBD4FC)
    private val onTertiaryDarkMediumContrast = Color(0xFF2E1F3D)
    private val tertiaryContainerDarkMediumContrast = Color(0xFF9D89AE)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF101418)
    private val onBackgroundDarkMediumContrast = Color(0xFFE0E2E8)
    private val surfaceDarkMediumContrast = Color(0xFF101418)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF42474E)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFD8DCE5)
    private val outlineDarkMediumContrast = Color(0xFFAEB2BA)
    private val outlineVariantDarkMediumContrast = Color(0xFF8C9198)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFE0E2E8)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF272A2F)
    private val inversePrimaryDarkMediumContrast = Color(0xFF164B75)
    private val surfaceDimDarkMediumContrast = Color(0xFF101418)
    private val surfaceBrightDarkMediumContrast = Color(0xFF424549)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF05080B)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E22)
    private val surfaceContainerDarkMediumContrast = Color(0xFF25282D)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF303337)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3E43)
    private val primaryDarkHighContrast = Color(0xFFE7F1FF)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFF9AC6F8)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF000C1A)
    private val secondaryDarkHighContrast = Color(0xFFE7F1FF)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFB6C4D7)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF010C19)
    private val tertiaryDarkHighContrast = Color(0xFFF9EBFF)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFD1BAE1)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF130421)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF101418)
    private val onBackgroundDarkHighContrast = Color(0xFFE0E2E8)
    private val surfaceDarkHighContrast = Color(0xFF101418)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF42474E)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFECF0F9)
    private val outlineVariantDarkHighContrast = Color(0xFFBEC3CB)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFE0E2E8)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF164B75)
    private val surfaceDimDarkHighContrast = Color(0xFF101418)
    private val surfaceBrightDarkHighContrast = Color(0xFF4D5055)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF1D2024)
    private val surfaceContainerDarkHighContrast = Color(0xFF2D3135)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF383C40)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF44474C)

    override val light: ColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    override val dark: ColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    override val lightMedium: ColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    override val lightHigh: ColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    override val darkMedium: ColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    override val darkHigh: ColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}
