// AUTO-GENERATED from Material Theme Builder export "material-theme1-danshuRed". DO NOT EDIT BY HAND.
// 色值逐字搬自 MTB 导出（未自造）；重生成见 scripts/gen_schemes.mjs + Phase 3 audit。
package com.example.flikky.ui.theme.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** DanshuRed 主题的 6 套 MD3 ColorScheme（light/dark × 标准/中/高对比度）。 */
internal object DanshuRedScheme : ThemeScheme {
    private val primaryLight = Color(0xFF8F4A4C)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFFFDAD9)
    private val onPrimaryContainerLight = Color(0xFF733335)
    private val secondaryLight = Color(0xFF775656)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFFFDAD9)
    private val onSecondaryContainerLight = Color(0xFF5D3F3F)
    private val tertiaryLight = Color(0xFF755A2F)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFFFDDAF)
    private val onTertiaryContainerLight = Color(0xFF5B421A)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFFFF8F7)
    private val onBackgroundLight = Color(0xFF221919)
    private val surfaceLight = Color(0xFFFFF8F7)
    private val onSurfaceLight = Color(0xFF221919)
    private val surfaceVariantLight = Color(0xFFF4DDDC)
    private val onSurfaceVariantLight = Color(0xFF524343)
    private val outlineLight = Color(0xFF857372)
    private val outlineVariantLight = Color(0xFFD7C1C1)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF382E2E)
    private val inverseOnSurfaceLight = Color(0xFFFFEDEC)
    private val inversePrimaryLight = Color(0xFFFFB3B3)
    private val surfaceDimLight = Color(0xFFE8D6D5)
    private val surfaceBrightLight = Color(0xFFFFF8F7)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFFFF0EF)
    private val surfaceContainerLight = Color(0xFFFCEAE9)
    private val surfaceContainerHighLight = Color(0xFFF6E4E3)
    private val surfaceContainerHighestLight = Color(0xFFF0DEDE)
    private val primaryLightMediumContrast = Color(0xFF5E2326)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFFA1585A)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF4A2F2F)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF876564)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF48320A)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF85683C)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFFFF8F7)
    private val onBackgroundLightMediumContrast = Color(0xFF221919)
    private val surfaceLightMediumContrast = Color(0xFFFFF8F7)
    private val onSurfaceLightMediumContrast = Color(0xFF170F0F)
    private val surfaceVariantLightMediumContrast = Color(0xFFF4DDDC)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF413333)
    private val outlineLightMediumContrast = Color(0xFF5F4F4E)
    private val outlineVariantLightMediumContrast = Color(0xFF7A6969)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF382E2E)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDEC)
    private val inversePrimaryLightMediumContrast = Color(0xFFFFB3B3)
    private val surfaceDimLightMediumContrast = Color(0xFFD4C3C2)
    private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0EF)
    private val surfaceContainerLightMediumContrast = Color(0xFFF6E4E3)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFEBD9D8)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFDFCECD)
    private val primaryLightHighContrast = Color(0xFF51191D)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF763538)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF3F2525)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF5F4141)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF3D2802)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF5E451C)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFFFF8F7)
    private val onBackgroundLightHighContrast = Color(0xFF221919)
    private val surfaceLightHighContrast = Color(0xFFFFF8F7)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFF4DDDC)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF362929)
    private val outlineVariantLightHighContrast = Color(0xFF554545)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF382E2E)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFFFFB3B3)
    private val surfaceDimLightHighContrast = Color(0xFFC5B5B4)
    private val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFFFEDEC)
    private val surfaceContainerLightHighContrast = Color(0xFFF0DEDE)
    private val surfaceContainerHighLightHighContrast = Color(0xFFE2D0D0)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFD4C3C2)
    private val primaryDark = Color(0xFFFFB3B3)
    private val onPrimaryDark = Color(0xFF561D21)
    private val primaryContainerDark = Color(0xFF733335)
    private val onPrimaryContainerDark = Color(0xFFFFDAD9)
    private val secondaryDark = Color(0xFFE6BDBC)
    private val onSecondaryDark = Color(0xFF442929)
    private val secondaryContainerDark = Color(0xFF5D3F3F)
    private val onSecondaryContainerDark = Color(0xFFFFDAD9)
    private val tertiaryDark = Color(0xFFE5C18D)
    private val onTertiaryDark = Color(0xFF422C05)
    private val tertiaryContainerDark = Color(0xFF5B421A)
    private val onTertiaryContainerDark = Color(0xFFFFDDAF)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF1A1111)
    private val onBackgroundDark = Color(0xFFF0DEDE)
    private val surfaceDark = Color(0xFF1A1111)
    private val onSurfaceDark = Color(0xFFF0DEDE)
    private val surfaceVariantDark = Color(0xFF524343)
    private val onSurfaceVariantDark = Color(0xFFD7C1C1)
    private val outlineDark = Color(0xFFA08C8C)
    private val outlineVariantDark = Color(0xFF524343)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFF0DEDE)
    private val inverseOnSurfaceDark = Color(0xFF382E2E)
    private val inversePrimaryDark = Color(0xFF8F4A4C)
    private val surfaceDimDark = Color(0xFF1A1111)
    private val surfaceBrightDark = Color(0xFF423736)
    private val surfaceContainerLowestDark = Color(0xFF140C0C)
    private val surfaceContainerLowDark = Color(0xFF221919)
    private val surfaceContainerDark = Color(0xFF271D1D)
    private val surfaceContainerHighDark = Color(0xFF322827)
    private val surfaceContainerHighestDark = Color(0xFF3D3232)
    private val primaryDarkMediumContrast = Color(0xFFFFD1D1)
    private val onPrimaryDarkMediumContrast = Color(0xFF481217)
    private val primaryContainerDarkMediumContrast = Color(0xFFCB7A7C)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFFDD2D1)
    private val onSecondaryDarkMediumContrast = Color(0xFF381F1F)
    private val secondaryContainerDarkMediumContrast = Color(0xFFAD8887)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFFCD7A1)
    private val onTertiaryDarkMediumContrast = Color(0xFF352200)
    private val tertiaryContainerDarkMediumContrast = Color(0xFFAB8C5C)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF1A1111)
    private val onBackgroundDarkMediumContrast = Color(0xFFF0DEDE)
    private val surfaceDarkMediumContrast = Color(0xFF1A1111)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF524343)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFEED7D6)
    private val outlineDarkMediumContrast = Color(0xFFC2ADAC)
    private val outlineVariantDarkMediumContrast = Color(0xFF9F8C8B)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFF0DEDE)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF322827)
    private val inversePrimaryDarkMediumContrast = Color(0xFF743437)
    private val surfaceDimDarkMediumContrast = Color(0xFF1A1111)
    private val surfaceBrightDarkMediumContrast = Color(0xFF4D4241)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0606)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF251B1B)
    private val surfaceContainerDarkMediumContrast = Color(0xFF2F2525)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF3B3030)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF463B3B)
    private val primaryDarkHighContrast = Color(0xFFFFECEB)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFFFFADAE)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF220003)
    private val secondaryDarkHighContrast = Color(0xFFFFECEB)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFE2B9B8)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF190606)
    private val tertiaryDarkHighContrast = Color(0xFFFFEDD8)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFE1BD89)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF130900)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF1A1111)
    private val onBackgroundDarkHighContrast = Color(0xFFF0DEDE)
    private val surfaceDarkHighContrast = Color(0xFF1A1111)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF524343)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFFFECEB)
    private val outlineVariantDarkHighContrast = Color(0xFFD3BEBD)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFF0DEDE)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF743437)
    private val surfaceDimDarkHighContrast = Color(0xFF1A1111)
    private val surfaceBrightDarkHighContrast = Color(0xFF594D4D)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF271D1D)
    private val surfaceContainerDarkHighContrast = Color(0xFF382E2E)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF443939)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF504444)

    override val light: ColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    override val dark: ColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    override val lightMedium: ColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    override val lightHigh: ColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    override val darkMedium: ColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    override val darkHigh: ColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}
