// AUTO-GENERATED from Material Theme Builder export "material-theme2-danziRed". DO NOT EDIT BY HAND.
// 色值逐字搬自 MTB 导出（未自造）；重生成见 scripts/gen_schemes.mjs + Phase 3 audit。
package com.example.flikky.ui.theme.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** DanziRed 主题的 6 套 MD3 ColorScheme（light/dark × 标准/中/高对比度）。 */
internal object DanziRedScheme : ThemeScheme {
    private val primaryLight = Color(0xFF8B4A63)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFFFD9E4)
    private val onPrimaryContainerLight = Color(0xFF6F334B)
    private val secondaryLight = Color(0xFF735760)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFFFD9E4)
    private val onSecondaryContainerLight = Color(0xFF5A3F48)
    private val tertiaryLight = Color(0xFF7D5636)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFFFDCC4)
    private val onTertiaryContainerLight = Color(0xFF623F21)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFFFF8F8)
    private val onBackgroundLight = Color(0xFF22191C)
    private val surfaceLight = Color(0xFFFFF8F8)
    private val onSurfaceLight = Color(0xFF22191C)
    private val surfaceVariantLight = Color(0xFFF2DDE2)
    private val onSurfaceVariantLight = Color(0xFF514347)
    private val outlineLight = Color(0xFF837377)
    private val outlineVariantLight = Color(0xFFD5C2C6)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF372E31)
    private val inverseOnSurfaceLight = Color(0xFFFDEDF0)
    private val inversePrimaryLight = Color(0xFFFFB0CC)
    private val surfaceDimLight = Color(0xFFE6D6D9)
    private val surfaceBrightLight = Color(0xFFFFF8F8)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFFFF0F3)
    private val surfaceContainerLight = Color(0xFFFAEAED)
    private val surfaceContainerHighLight = Color(0xFFF4E4E7)
    private val surfaceContainerHighestLight = Color(0xFFEEDFE2)
    private val primaryLightMediumContrast = Color(0xFF5B233B)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF9C5872)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF482F38)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF83656F)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF4F2E12)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF8E6444)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFFFF8F8)
    private val onBackgroundLightMediumContrast = Color(0xFF22191C)
    private val surfaceLightMediumContrast = Color(0xFFFFF8F8)
    private val onSurfaceLightMediumContrast = Color(0xFF170F11)
    private val surfaceVariantLightMediumContrast = Color(0xFFF2DDE2)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF3F3337)
    private val outlineLightMediumContrast = Color(0xFF5D4F53)
    private val outlineVariantLightMediumContrast = Color(0xFF79696D)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF372E31)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFFDEDF0)
    private val inversePrimaryLightMediumContrast = Color(0xFFFFB0CC)
    private val surfaceDimLightMediumContrast = Color(0xFFD2C3C6)
    private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F8)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0F3)
    private val surfaceContainerLightMediumContrast = Color(0xFFF4E4E7)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFE9D9DC)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFDDCED1)
    private val primaryLightHighContrast = Color(0xFF4E1830)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF72354E)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF3D252E)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF5D424B)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF432509)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF654123)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFFFF8F8)
    private val onBackgroundLightHighContrast = Color(0xFF22191C)
    private val surfaceLightHighContrast = Color(0xFFFFF8F8)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFF2DDE2)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF35292D)
    private val outlineVariantLightHighContrast = Color(0xFF53464A)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF372E31)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFFFFB0CC)
    private val surfaceDimLightHighContrast = Color(0xFFC4B5B8)
    private val surfaceBrightLightHighContrast = Color(0xFFFFF8F8)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFFDEDF0)
    private val surfaceContainerLightHighContrast = Color(0xFFEEDFE2)
    private val surfaceContainerHighLightHighContrast = Color(0xFFE0D1D4)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFD2C3C6)
    private val primaryDark = Color(0xFFFFB0CC)
    private val onPrimaryDark = Color(0xFF541D35)
    private val primaryContainerDark = Color(0xFF6F334B)
    private val onPrimaryContainerDark = Color(0xFFFFD9E4)
    private val secondaryDark = Color(0xFFE2BDC8)
    private val onSecondaryDark = Color(0xFF422932)
    private val secondaryContainerDark = Color(0xFF5A3F48)
    private val onSecondaryContainerDark = Color(0xFFFFD9E4)
    private val tertiaryDark = Color(0xFFF0BC95)
    private val onTertiaryDark = Color(0xFF48290D)
    private val tertiaryContainerDark = Color(0xFF623F21)
    private val onTertiaryContainerDark = Color(0xFFFFDCC4)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF191114)
    private val onBackgroundDark = Color(0xFFEEDFE2)
    private val surfaceDark = Color(0xFF191114)
    private val onSurfaceDark = Color(0xFFEEDFE2)
    private val surfaceVariantDark = Color(0xFF514347)
    private val onSurfaceVariantDark = Color(0xFFD5C2C6)
    private val outlineDark = Color(0xFF9D8C91)
    private val outlineVariantDark = Color(0xFF514347)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFEEDFE2)
    private val inverseOnSurfaceDark = Color(0xFF372E31)
    private val inversePrimaryDark = Color(0xFF8B4A63)
    private val surfaceDimDark = Color(0xFF191114)
    private val surfaceBrightDark = Color(0xFF403739)
    private val surfaceContainerLowestDark = Color(0xFF130C0F)
    private val surfaceContainerLowDark = Color(0xFF22191C)
    private val surfaceContainerDark = Color(0xFF261D20)
    private val surfaceContainerHighDark = Color(0xFF31282A)
    private val surfaceContainerHighestDark = Color(0xFF3C3235)
    private val primaryDarkMediumContrast = Color(0xFFFFD0DF)
    private val onPrimaryDarkMediumContrast = Color(0xFF46122A)
    private val primaryContainerDarkMediumContrast = Color(0xFFC47B96)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFF9D3DE)
    private val onSecondaryDarkMediumContrast = Color(0xFF361F27)
    private val secondaryContainerDarkMediumContrast = Color(0xFFA98892)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFFFD4B5)
    private val onTertiaryDarkMediumContrast = Color(0xFF3C1E04)
    private val tertiaryContainerDarkMediumContrast = Color(0xFFB58764)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF191114)
    private val onBackgroundDarkMediumContrast = Color(0xFFEEDFE2)
    private val surfaceDarkMediumContrast = Color(0xFF191114)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF514347)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFEBD7DC)
    private val outlineDarkMediumContrast = Color(0xFFC0ADB2)
    private val outlineVariantDarkMediumContrast = Color(0xFF9D8C90)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFEEDFE2)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF31282A)
    private val inversePrimaryDarkMediumContrast = Color(0xFF70344D)
    private val surfaceDimDarkMediumContrast = Color(0xFF191114)
    private val surfaceBrightDarkMediumContrast = Color(0xFF4C4245)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0608)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF241B1E)
    private val surfaceContainerDarkMediumContrast = Color(0xFF2E2628)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF393033)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF453B3E)
    private val primaryDarkHighContrast = Color(0xFFFFEBF0)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFFFCABC8)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF20000E)
    private val secondaryDarkHighContrast = Color(0xFFFFEBF0)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFDEB9C4)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF18060D)
    private val tertiaryDarkHighContrast = Color(0xFFFFEDE1)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFECB892)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF170700)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF191114)
    private val onBackgroundDarkHighContrast = Color(0xFFEEDFE2)
    private val surfaceDarkHighContrast = Color(0xFF191114)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF514347)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFFFEBF0)
    private val outlineVariantDarkHighContrast = Color(0xFFD1BEC2)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFEEDFE2)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF70344D)
    private val surfaceDimDarkHighContrast = Color(0xFF191114)
    private val surfaceBrightDarkHighContrast = Color(0xFF584D50)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF261D20)
    private val surfaceContainerDarkHighContrast = Color(0xFF372E31)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF43393C)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF4E4447)

    override val light: ColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    override val dark: ColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    override val lightMedium: ColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    override val lightHigh: ColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    override val darkMedium: ColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    override val darkHigh: ColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}
