// AUTO-GENERATED from Material Theme Builder export "material-theme8-jiehuaPurple". DO NOT EDIT BY HAND.
// 色值逐字搬自 MTB 导出（未自造）；重生成见 scripts/gen_schemes.mjs + Phase 3 audit。
package com.example.flikky.ui.theme.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** JiehuaPurple 主题的 6 套 MD3 ColorScheme（light/dark × 标准/中/高对比度）。 */
internal object JiehuaPurpleScheme : ThemeScheme {
    private val primaryLight = Color(0xFF844C72)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFFFD8EE)
    private val onPrimaryContainerLight = Color(0xFF69345A)
    private val secondaryLight = Color(0xFF705766)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFFADAEB)
    private val onSecondaryContainerLight = Color(0xFF57404E)
    private val tertiaryLight = Color(0xFF81533F)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFFFDBCD)
    private val onTertiaryContainerLight = Color(0xFF653C2A)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFFFF8F9)
    private val onBackgroundLight = Color(0xFF201A1D)
    private val surfaceLight = Color(0xFFFFF8F9)
    private val onSurfaceLight = Color(0xFF201A1D)
    private val surfaceVariantLight = Color(0xFFEFDEE6)
    private val onSurfaceVariantLight = Color(0xFF4F444A)
    private val outlineLight = Color(0xFF81737A)
    private val outlineVariantLight = Color(0xFFD3C2CA)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF362E32)
    private val inverseOnSurfaceLight = Color(0xFFFBEDF3)
    private val inversePrimaryLight = Color(0xFFF7B1DE)
    private val surfaceDimLight = Color(0xFFE4D7DC)
    private val surfaceBrightLight = Color(0xFFFFF8F9)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFFEF0F5)
    private val surfaceContainerLight = Color(0xFFF8EAF0)
    private val surfaceContainerHighLight = Color(0xFFF2E5EA)
    private val surfaceContainerHighestLight = Color(0xFFEDDFE4)
    private val primaryLightMediumContrast = Color(0xFF562448)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF955A82)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF45303D)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF7F6675)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF522C1B)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF91624D)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFFFF8F9)
    private val onBackgroundLightMediumContrast = Color(0xFF201A1D)
    private val surfaceLightMediumContrast = Color(0xFFFFF8F9)
    private val onSurfaceLightMediumContrast = Color(0xFF160F13)
    private val surfaceVariantLightMediumContrast = Color(0xFFEFDEE6)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF3E3339)
    private val outlineLightMediumContrast = Color(0xFF5B4F55)
    private val outlineVariantLightMediumContrast = Color(0xFF776970)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF362E32)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFFBEDF3)
    private val inversePrimaryLightMediumContrast = Color(0xFFF7B1DE)
    private val surfaceDimLightMediumContrast = Color(0xFFD0C3C8)
    private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F9)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFFEF0F5)
    private val surfaceContainerLightMediumContrast = Color(0xFFF2E5EA)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFE7D9DF)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFDBCED3)
    private val primaryLightHighContrast = Color(0xFF4A1A3E)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF6C375C)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF3A2633)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF594250)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF462312)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF683F2C)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFFFF8F9)
    private val onBackgroundLightHighContrast = Color(0xFF201A1D)
    private val surfaceLightHighContrast = Color(0xFFFFF8F9)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFEFDEE6)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF33292F)
    private val outlineVariantLightHighContrast = Color(0xFF51464C)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF362E32)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFFF7B1DE)
    private val surfaceDimLightHighContrast = Color(0xFFC2B5BB)
    private val surfaceBrightLightHighContrast = Color(0xFFFFF8F9)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFFBEDF3)
    private val surfaceContainerLightHighContrast = Color(0xFFEDDFE4)
    private val surfaceContainerHighLightHighContrast = Color(0xFFDED1D6)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFD0C3C8)
    private val primaryDark = Color(0xFFF7B1DE)
    private val onPrimaryDark = Color(0xFF4F1E42)
    private val primaryContainerDark = Color(0xFF69345A)
    private val onPrimaryContainerDark = Color(0xFFFFD8EE)
    private val secondaryDark = Color(0xFFDDBECF)
    private val onSecondaryDark = Color(0xFF3F2A37)
    private val secondaryContainerDark = Color(0xFF57404E)
    private val onSecondaryContainerDark = Color(0xFFFADAEB)
    private val tertiaryDark = Color(0xFFF4B9A0)
    private val onTertiaryDark = Color(0xFF4B2716)
    private val tertiaryContainerDark = Color(0xFF653C2A)
    private val onTertiaryContainerDark = Color(0xFFFFDBCD)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF181215)
    private val onBackgroundDark = Color(0xFFEDDFE4)
    private val surfaceDark = Color(0xFF181215)
    private val onSurfaceDark = Color(0xFFEDDFE4)
    private val surfaceVariantDark = Color(0xFF4F444A)
    private val onSurfaceVariantDark = Color(0xFFD3C2CA)
    private val outlineDark = Color(0xFF9B8D94)
    private val outlineVariantDark = Color(0xFF4F444A)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFEDDFE4)
    private val inverseOnSurfaceDark = Color(0xFF362E32)
    private val inversePrimaryDark = Color(0xFF844C72)
    private val surfaceDimDark = Color(0xFF181215)
    private val surfaceBrightDark = Color(0xFF3F373B)
    private val surfaceContainerLowestDark = Color(0xFF130C10)
    private val surfaceContainerLowDark = Color(0xFF201A1D)
    private val surfaceContainerDark = Color(0xFF251E22)
    private val surfaceContainerHighDark = Color(0xFF2F282C)
    private val surfaceContainerHighestDark = Color(0xFF3B3337)
    private val primaryDarkMediumContrast = Color(0xFFFFCFEB)
    private val onPrimaryDarkMediumContrast = Color(0xFF421337)
    private val primaryContainerDarkMediumContrast = Color(0xFFBC7DA6)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFF4D4E5)
    private val onSecondaryDarkMediumContrast = Color(0xFF33202C)
    private val secondaryContainerDarkMediumContrast = Color(0xFFA58999)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFFFD3C1)
    private val onTertiaryDarkMediumContrast = Color(0xFF3E1C0C)
    private val tertiaryContainerDarkMediumContrast = Color(0xFFB9856E)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF181215)
    private val onBackgroundDarkMediumContrast = Color(0xFFEDDFE4)
    private val surfaceDarkMediumContrast = Color(0xFF181215)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF4F444A)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFE9D8DF)
    private val outlineDarkMediumContrast = Color(0xFFBDAEB5)
    private val outlineVariantDarkMediumContrast = Color(0xFF9B8C93)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFEDDFE4)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2F282C)
    private val inversePrimaryDarkMediumContrast = Color(0xFF6B365B)
    private val surfaceDimDarkMediumContrast = Color(0xFF181215)
    private val surfaceBrightDarkMediumContrast = Color(0xFF4B4246)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0B0609)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF231C1F)
    private val surfaceContainerDarkMediumContrast = Color(0xFF2D262A)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF383035)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF443B40)
    private val primaryDarkHighContrast = Color(0xFFFFEBF4)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFFF3AEDA)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF1E0017)
    private val secondaryDarkHighContrast = Color(0xFFFFEBF4)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFD9BACB)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF160611)
    private val tertiaryDarkHighContrast = Color(0xFFFFECE5)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFF0B59C)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF1B0500)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF181215)
    private val onBackgroundDarkHighContrast = Color(0xFFEDDFE4)
    private val surfaceDarkHighContrast = Color(0xFF181215)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF4F444A)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFFDEBF3)
    private val outlineVariantDarkHighContrast = Color(0xFFCFBEC6)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFEDDFE4)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF6B365B)
    private val surfaceDimDarkHighContrast = Color(0xFF181215)
    private val surfaceBrightDarkHighContrast = Color(0xFF574E52)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF251E22)
    private val surfaceContainerDarkHighContrast = Color(0xFF362E32)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF41393D)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF4D4449)

    override val light: ColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    override val dark: ColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    override val lightMedium: ColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    override val lightHigh: ColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    override val darkMedium: ColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    override val darkHigh: ColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}
