// One-shot generator: emit the web-side design-token file (tokens.css) FROM the
// App-side Kotlin token constants, so a shape/spacing change lives in exactly one
// place (the .kt sources) and both platforms stay in sync. Run after editing
// Shape.kt / Spacing.kt:  node scripts/gen_web_tokens.mjs
//
// Colors are intentionally NOT emitted here: app.css already uses
// rgb(var(--mdui-color-*)), and the phone pushes the theme seed via peer-info so
// MDUI re-derives a matching palette (shared Material Color Utilities). Typography
// maps onto MDUI's own --mdui-typescale-* (already value-identical to the App's MD3
// scale), so it needs no per-value emission — only stable semantic aliases.
import { readFileSync, writeFileSync } from 'node:fs';

const APP = 'E:/BSoftware/AndroidProject/Flikky/app/src/main/java/com/example/flikky';
const OUT = 'E:/BSoftware/AndroidProject/Flikky/app/src/main/assets/web/tokens.css';

// --- Parse App token constants (single source of truth) ---------------------

// Shape.kt:  extraSmall = RoundedCornerShape(8.dp), ...
function parseShapes() {
  const kt = readFileSync(`${APP}/ui/theme/Shape.kt`, 'utf8');
  const re = /(\w+)\s*=\s*RoundedCornerShape\((\d+)\.dp\)/g;
  const map = {};
  let m;
  while ((m = re.exec(kt)) !== null) map[m[1]] = Number(m[2]);
  return map; // { extraSmall, small, medium, large, extraLarge }
}

// Spacing.kt:  val xs = 4.dp, ...  (only the raw-dp tokens; aliases handled below)
function parseSpacing() {
  const kt = readFileSync(`${APP}/ui/theme/Spacing.kt`, 'utf8');
  const re = /val (\w+)\s*=\s*(\d+)\.dp/g;
  const map = {};
  let m;
  while ((m = re.exec(kt)) !== null) map[m[1]] = Number(m[2]);
  return map; // { xs, sm, md, lg, xl, xxl, xxxl }
}

// FlikkySettings.kt:  const val BUBBLE_CORNER_DEFAULT = 18
function parseBubbleDefault() {
  const kt = readFileSync(`${APP}/data/settings/FlikkySettings.kt`, 'utf8');
  const m = kt.match(/const val BUBBLE_CORNER_DEFAULT\s*=\s*(\d+)/);
  if (!m) throw new Error('BUBBLE_CORNER_DEFAULT not found in FlikkySettings.kt');
  return Number(m[1]);
}

const shapes = parseShapes();
const spacing = parseSpacing();
const bubbleDefault = parseBubbleDefault();

// --- Sanity checks (fail loud on drift, mirroring gen_schemes.mjs) -----------

const SHAPE_KEYS = ['extraSmall', 'small', 'medium', 'large', 'extraLarge'];
const SPACE_KEYS = ['xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'];
for (const k of SHAPE_KEYS) {
  if (typeof shapes[k] !== 'number') throw new Error(`Shape.kt missing token: ${k}`);
}
for (const k of SPACE_KEYS) {
  if (typeof spacing[k] !== 'number') throw new Error(`Spacing.kt missing token: ${k}`);
}
if (bubbleDefault < 8 || bubbleDefault > 28) {
  throw new Error(`BUBBLE_CORNER_DEFAULT ${bubbleDefault} outside expected 8..28`);
}

// --- Emit tokens.css ---------------------------------------------------------

const out = `/* AUTO-GENERATED by scripts/gen_web_tokens.mjs from the App Kotlin token
 * constants (ui/theme/Shape.kt, ui/theme/Spacing.kt, data/settings/FlikkySettings.kt).
 * DO NOT EDIT BY HAND — edit the .kt sources and re-run the script.
 *
 * Flikky 跨端共享 design token —— Web 侧单一事实源（SSOT）。两端一致的做法：
 * 改 App 的 Shape.kt / Spacing.kt 常量 → 重跑 node scripts/gen_web_tokens.mjs → 两端同步。
 *
 * 颜色不在此层：app.css 已全用 rgb(var(--mdui-color-*))，手机通过 peer-info 推 seed，
 * MDUI 用 Material Color Utilities 从同一 seed 重算 → 双端同色相。
 * 排版复用 MDUI 自带 --mdui-typescale-*（已与 App MD3 type scale 逐值相等），此处只留语义别名。
 */

:root {
  /* ── Shape（对齐 Shape.kt）── 用自有 --flikky-shape-* 精确对齐 App 档位
   * （App small=${shapes.small}dp vs MDUI shape-corner-small=8px）。 */
  --flikky-shape-xs: ${shapes.extraSmall}px;
  --flikky-shape-sm: ${shapes.small}px;
  --flikky-shape-md: ${shapes.medium}px;
  --flikky-shape-lg: ${shapes.large}px;
  --flikky-shape-xl: ${shapes.extraLarge}px;

  /* ── Spacing（对齐 Spacing.kt 的 T 恤尺码 + 语义别名）── */
  --flikky-space-xs: ${spacing.xs}px;
  --flikky-space-sm: ${spacing.sm}px;
  --flikky-space-md: ${spacing.md}px;
  --flikky-space-lg: ${spacing.lg}px;
  --flikky-space-xl: ${spacing.xl}px;
  --flikky-space-xxl: ${spacing.xxl}px;
  --flikky-space-xxxl: ${spacing.xxxl}px;
  /* 语义别名（对齐 Spacing.kt 的 screenEdge / listGap / sectionGap） */
  --flikky-space-screen-edge: var(--flikky-space-lg);   /* ${spacing.lg}px */
  --flikky-space-list-gap: var(--flikky-space-sm);      /* ${spacing.sm}px  */
  --flikky-space-section-gap: var(--flikky-space-xxl);  /* ${spacing.xxl}px */

  /* ── Typography（映射到 MDUI 自带 typescale，与 App MD3 scale 逐值相等）── */
  --flikky-font-body-small: var(--mdui-typescale-body-small-size);
  --flikky-font-body-medium: var(--mdui-typescale-body-medium-size);
  --flikky-font-body-large: var(--mdui-typescale-body-large-size);
  --flikky-font-label-large: var(--mdui-typescale-label-large-size);
  --flikky-font-title-medium: var(--mdui-typescale-title-medium-size);
  --flikky-font-title-large: var(--mdui-typescale-title-large-size);

  /* ── 气泡圆角（默认值；运行时由 app.js 从 peer-info 的 bubbleCornerRadius 覆写）──
   * 「一个设计决策一处改动两端生效」的活样例：手机拖 slider → 浏览器实时改圆角。 */
  --flikky-bubble-radius: ${bubbleDefault}px;
}
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
console.log(`  shapes: ${SHAPE_KEYS.map((k) => `${k}=${shapes[k]}`).join(', ')}`);
console.log(`  spacing: ${SPACE_KEYS.map((k) => `${k}=${spacing[k]}`).join(', ')}`);
console.log(`  bubble default: ${bubbleDefault}`);
