#!/usr/bin/env node
/**
 * Generates browser clip paths from geometry exported by LeadingShapeExportTest
 * from the official MaterialShapes library.
 *
 * The previous generator could reproduce one star formula, but the selected
 * catalogue includes tuned shapes such as arch and ghostish that have no
 * equivalent formula to copy safely.
 *
 * MaterialShapes and RoundedPolygon.cubics are experimental APIs and have
 * moved between Material3 releases. After an upgrade, run the JVM fixture
 * verification before accepting any generated diff.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FIXTURE = join(ROOT, 'app/src/test/resources/leading-shapes.json');
const OUT = join(ROOT, 'app/src/main/assets/web/shapes.svg.html');

const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));

function number(value) {
  const rounded = Number(Number(value).toFixed(6));
  return Object.is(rounded, -0) ? '0' : String(rounded);
}

function pathFor(cubics) {
  if (!Array.isArray(cubics) || cubics.length === 0) {
    throw new Error('shape has no cubic geometry');
  }
  const first = cubics[0];
  const commands = [`M ${number(first[0])} ${number(first[1])}`];
  for (const cubic of cubics) {
    if (!Array.isArray(cubic) || cubic.length !== 8) {
      throw new Error('each cubic must contain 8 coordinates');
    }
    commands.push(
      `C ${number(cubic[2])} ${number(cubic[3])} ` +
      `${number(cubic[4])} ${number(cubic[5])} ` +
      `${number(cubic[6])} ${number(cubic[7])}`,
    );
  }
  commands.push('Z');
  return commands.join(' ');
}

const generated = Object.entries(fixture.shapes).map(([id, shape]) => ({
  id,
  path: pathFor(shape.cubics),
}));
const cookie9 = generated.find((shape) => shape.id === 'cookie9Sided');
if (!cookie9) throw new Error('fixture is missing cookie9Sided');

const clips = generated.map(({ id, path }) =>
  `    <clipPath id="flikky-shape-${id}" clipPathUnits="objectBoundingBox">\n` +
  `      <path d="${path}"/>\n` +
  '    </clipPath>',
);
clips.push(
  '    <clipPath id="flikky-cookie9" clipPathUnits="objectBoundingBox">\n' +
  `      <path d="${cookie9.path}"/>\n` +
  '    </clipPath>',
);

const out = `<!-- AUTO-GENERATED by scripts/gen_web_shapes.mjs. DO NOT EDIT BY HAND.
     Geometry comes from official MaterialShapes via leading-shapes.json.
     flikky-cookie9 remains as a compatibility alias until all CSS reads the shared variable. -->
<svg width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute">
  <defs>
${clips.join('\n')}
  </defs>
</svg>
`;

writeFileSync(OUT, out);
console.log(`Wrote ${generated.length} shapes plus 1 alias to ${OUT}`);
