#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fixturePath = join(root, 'app/src/test/resources/leading-types.json');
const outputPath = join(root, 'app/src/main/assets/web/leading-types.js');
const cssOutputPath = join(root, 'app/src/main/assets/web/leading-types.css');
const types = JSON.parse(readFileSync(fixturePath, 'utf8'));

const output = `// AUTO-GENERATED by scripts/gen_web_leading.mjs. DO NOT EDIT BY HAND.\n` +
  `globalThis.flikkyLeadingTypes = Object.freeze(${JSON.stringify(types, null, 2)});\n`;

writeFileSync(outputPath, output);

const css = `/* AUTO-GENERATED by scripts/gen_web_leading.mjs. DO NOT EDIT BY HAND. */\n` +
  types.map((type) => `.fk-item[data-leading-type="${type.id}"] .fk-item-lead,\n` +
    `.file-bubble .file-icon[data-leading-type="${type.id}"],\n` +
    `.bubble-row.me .file-bubble .file-icon[data-leading-type="${type.id}"] {\n` +
    `  background: var(--flikky-leading-bg-${type.id}, rgb(var(--mdui-color-secondary-container)));\n` +
    `  color: var(--flikky-leading-fg-${type.id}, rgb(var(--mdui-color-on-secondary-container)));\n` +
    `}`).join('\n\n') + '\n';

writeFileSync(cssOutputPath, css);
console.log(`Wrote ${types.length} leading types to ${outputPath} and ${cssOutputPath}`);
