/**
 * 复刻 M3 Expressive 官方异形 MaterialShapes.Cookie9Sided → SVG clipPath。
 *
 * 为什么要复刻而不是手画：App 的文件分类图标容器用的就是
 * `MaterialShapes.Cookie9Sided`（ui/components/FileLeadingVisual.kt:52）。
 * 浏览器端必须是同一个形状，否则同一个文件在两端长得不一样。
 *
 * 官方定义（androidx compose material3 MaterialShapes.kt）：
 *   RoundedPolygon.star(numVerticesPerRadius = 9, innerRadius = .8f,
 *                       rounding = CornerRounding(radius = .5f))
 *     .transformed(rotateZ(-90°))
 *     .normalized()
 *
 * 复刻方式：18 个交替顶点（外半径 1.0 / 内半径 0.8）→ 逐角做「与两邻边相切的圆弧」
 * 倒角，半径按边长预算钳制（graphics-shapes 无 smoothing 时就是这个行为）→ 旋转 −90°
 * → 归一化到单位包围盒。输出 clipPathUnits="objectBoundingBox"，任意尺寸自适应。
 *
 * 运行：node scripts/gen_web_shapes.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'app/src/main/assets/web/shapes.svg.html');

const N = 9;
const INNER = 0.8;
const ROUND = 0.5;

/** 交替内外半径的 2N 个星形顶点。 */
function starVertices() {
  const pts = [];
  for (let i = 0; i < N * 2; i++) {
    const r = i % 2 === 0 ? 1 : INNER;
    const a = (Math.PI * i) / N - Math.PI / 2;  // 同时完成 rotateZ(-90°)
    pts.push([r * Math.cos(a), r * Math.sin(a)]);
  }
  return pts;
}

const sub = (a, b) => [a[0] - b[0], a[1] - b[1]];
const len = (v) => Math.hypot(v[0], v[1]);
const norm = (v) => { const l = len(v); return [v[0] / l, v[1] / l]; };
const add = (a, b) => [a[0] + b[0], a[1] + b[1]];
const mul = (v, s) => [v[0] * s, v[1] * s];
const cross = (a, b) => a[0] * b[1] - a[1] * b[0];

/**
 * 逐角倒圆：每个顶点用与两邻边相切的圆弧替换。
 * cut = r / tan(θ/2)（顶点到切点的距离，θ 为内角）；
 * 若某条边上两端 cut 之和超过边长，按比例同时缩小两端 —— 与 graphics-shapes 的钳制一致。
 */
function roundedPath(verts, radius) {
  const n = verts.length;
  const cuts = [];
  const radii = [];
  for (let i = 0; i < n; i++) {
    const prev = verts[(i - 1 + n) % n];
    const next = verts[(i + 1) % n];
    const d1 = norm(sub(prev, verts[i]));
    const d2 = norm(sub(next, verts[i]));
    const cosT = Math.max(-1, Math.min(1, d1[0] * d2[0] + d1[1] * d2[1]));
    const theta = Math.acos(cosT);            // 内角
    const cut = radius / Math.tan(theta / 2);
    cuts.push(cut);
    radii.push(radius);
  }
  // 按边长预算钳制：取全局统一系数，而不是逐边顺序缩放。
  // 顺序缩放会让先处理到的顶点被多缩一次，破坏星形本该有的 N 重对称
  // （表现为同类角出现 0.128 / 0.119 这种不该有的半径差异）。
  let k = 1;
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    const edge = len(sub(verts[j], verts[i]));
    const need = cuts[i] + cuts[j];
    if (need > edge) k = Math.min(k, edge / need);
  }
  for (let i = 0; i < n; i++) { cuts[i] *= k; radii[i] *= k; }

  let d = '';
  for (let i = 0; i < n; i++) {
    const prev = verts[(i - 1 + n) % n];
    const next = verts[(i + 1) % n];
    const d1 = norm(sub(prev, verts[i]));
    const d2 = norm(sub(next, verts[i]));
    const p1 = add(verts[i], mul(d1, cuts[i]));   // 入切点
    const p2 = add(verts[i], mul(d2, cuts[i]));   // 出切点
    const sweep = cross(d1, d2) > 0 ? 0 : 1;      // 凸角与凹角的弧方向不同
    if (i === 0) d += `M ${fmt(p1)} `;
    else d += `L ${fmt(p1)} `;
    d += `A ${f(radii[i])} ${f(radii[i])} 0 0 ${sweep} ${fmt(p2)} `;
  }
  return d + 'Z';
}

const f = (x) => Number(x.toFixed(5)).toString();
const fmt = (p) => `${f(p[0])} ${f(p[1])}`;

/** 归一化到 [0,1]×[0,1] 包围盒（objectBoundingBox 单位）。 */
function normalize(verts) {
  const xs = verts.map((p) => p[0]);
  const ys = verts.map((p) => p[1]);
  // 用顶点包围盒近似（外顶点即极值点，倒角只会向内收，误差可忽略）
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const minY = Math.min(...ys), maxY = Math.max(...ys);
  const s = 1 / Math.max(maxX - minX, maxY - minY);
  return verts.map(([x, y]) => [(x - minX) * s, (y - minY) * s]);
}

const verts = normalize(starVertices());
const path = roundedPath(verts, ROUND * (1 / 2));  // 半径同步缩放到归一化坐标系

const out = `<!-- AUTO-GENERATED by scripts/gen_web_shapes.mjs — DO NOT EDIT BY HAND.
     MaterialShapes.Cookie9Sided 的等价复刻，与 App 的文件图标容器同形。
     用法：<span class="flikky-shape-cookie9">…</span>，CSS 里 clip-path: url(#flikky-cookie9)。 -->
<svg width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute">
  <defs>
    <clipPath id="flikky-cookie9" clipPathUnits="objectBoundingBox">
      <path d="${path}"/>
    </clipPath>
  </defs>
</svg>
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
