/**
 * Compose spring (dampingRatio, stiffness) → CSS `linear()` easing + duration.
 *
 * 为什么需要这个：M3 Expressive 的手感来自弹簧物理（带回弹的 spatial spring），
 * CSS 的 cubic-bezier 数学上无法表达过冲（控制点被限制在 [0,1]），用 ease-out 近似
 * 会直接丢掉 Expressive 最有辨识度的那一下回弹。`linear()` 可以逐点采样任意曲线，
 * 是目前唯一能在纯 CSS 里精确还原 Compose spring 的方式。
 *
 * 物理模型与 Compose 一致：单位质量、初速度 0、从 0 运动到 1。
 *   ω0 = sqrt(stiffness / mass)
 *   欠阻尼 (ζ<1)：x(t) = 1 − e^(−ζω0t)·[cos(ωd·t) + (ζω0/ωd)·sin(ωd·t)],  ωd = ω0·√(1−ζ²)
 *   临界阻尼 (ζ=1)：x(t) = 1 − e^(−ω0t)·(1 + ω0t)
 *   过阻尼 (ζ>1)：双指数解
 *
 * 数值来源：docs/others/material-design-3-docs/theming/Motion.md（MD3 Expressive 六槽 spring）。
 * 运行：node scripts/gen_web_springs.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'app/src/main/assets/web/springs.css');

const MASS = 1;
const SETTLE = 0.001;   // 位移误差 < 0.1% 视为静止（对齐 Compose 的 visibilityThreshold 量级）
const MAX_T = 4;        // 安全上限（秒）
const SAMPLES = 48;     // linear() 采样点数：48 点足以让回弹平滑且不臃肿

/** MD3 Expressive motion tokens —— spatial 管位移/尺寸/形变，effects 管颜色/透明度。 */
const SPRINGS = {
  'spatial-fast':     { damping: 0.9, stiffness: 1400 },
  'spatial-default':  { damping: 0.9, stiffness: 700 },
  'spatial-slow':     { damping: 0.9, stiffness: 300 },
  'effects-fast':     { damping: 1.0, stiffness: 3800 },
  'effects-default':  { damping: 1.0, stiffness: 1600 },
  'effects-slow':     { damping: 1.0, stiffness: 800 },
};

function displacement(t, damping, stiffness) {
  const w0 = Math.sqrt(stiffness / MASS);
  const z = damping;
  if (z < 1) {
    const wd = w0 * Math.sqrt(1 - z * z);
    const e = Math.exp(-z * w0 * t);
    return 1 - e * (Math.cos(wd * t) + ((z * w0) / wd) * Math.sin(wd * t));
  }
  if (z === 1) {
    const e = Math.exp(-w0 * t);
    return 1 - e * (1 + w0 * t);
  }
  const s = w0 * Math.sqrt(z * z - 1);
  const r1 = -z * w0 + s;
  const r2 = -z * w0 - s;
  const A = r2 / (r1 - r2);
  const B = -r1 / (r1 - r2);
  return 1 + A * Math.exp(r1 * t) + B * Math.exp(r2 * t);
}

/** 二分找出「此后再也不越过 SETTLE 阈值」的时刻（对欠阻尼要扫过全部过冲峰）。 */
function settleTime(damping, stiffness) {
  const step = 1 / 2000;
  let last = 0;
  for (let t = 0; t <= MAX_T; t += step) {
    if (Math.abs(displacement(t, damping, stiffness) - 1) > SETTLE) last = t;
  }
  return Math.min(last + step, MAX_T);
}

function toLinear(damping, stiffness) {
  const dur = settleTime(damping, stiffness);
  const pts = [];
  for (let i = 0; i <= SAMPLES; i++) {
    const p = i / SAMPLES;
    pts.push(displacement(p * dur, damping, stiffness));
  }
  pts[0] = 0;
  pts[pts.length - 1] = 1;
  const body = pts.map((v) => v.toFixed(4).replace(/0+$/, '').replace(/\.$/, '')).join(', ');
  return { css: `linear(${body})`, ms: Math.round(dur * 1000) };
}

const lines = [
  '/* AUTO-GENERATED by scripts/gen_web_springs.mjs — DO NOT EDIT BY HAND.',
  ' * Compose/MD3 Expressive spring → CSS linear()。改 SPRINGS 常量后重跑脚本。',
  ' * 每条 spring 配一个 --*-dur：linear() 只定义曲线形状，时长仍由 transition-duration 给。',
  ' */',
  ':root {',
];
for (const [name, { damping, stiffness }] of Object.entries(SPRINGS)) {
  const { css, ms } = toLinear(damping, stiffness);
  lines.push(`  /* ζ=${damping} k=${stiffness} */`);
  lines.push(`  --flikky-spring-${name}: ${css};`);
  lines.push(`  --flikky-spring-${name}-dur: ${ms}ms;`);
}
lines.push('}');

const out = lines.join('\n') + '\n';
writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
