#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fixturePath = join(root, 'app/src/test/resources/leading-types.json');
const outputPath = join(root, 'app/src/main/assets/web/leading-types.js');
const types = JSON.parse(readFileSync(fixturePath, 'utf8'));

const output = `// AUTO-GENERATED by scripts/gen_web_leading.mjs. DO NOT EDIT BY HAND.\n` +
  `globalThis.flikkyLeadingTypes = Object.freeze(${JSON.stringify(types, null, 2)});\n`;

writeFileSync(outputPath, output);
console.log(`Wrote ${types.length} leading types to ${outputPath}`);
