package com.example.flikky.util

import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.double
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import kotlin.math.round

@OptIn(ExperimentalMaterial3ExpressiveApi::class)
class LeadingShapeExportTest {
    private val json = Json { prettyPrint = true }

    @Test
    fun exportTheShapeFixtureWhenAsked() {
        if (System.getProperty("flikky.exportShapes") != "true") return
        fixtureFile().writeText(
            json.encodeToString(JsonElement.serializer(), officialFixture()) + "\n",
            Charsets.UTF_8,
        )
    }

    @Test
    fun fixtureMatchesOfficialCubicsPointByPoint() {
        val shapes = fixtureRoot()["shapes"]!!.jsonObject
        LeadingShape.entries.forEach { shape ->
            val expected = officialCubics(shape)
            val actual = shapes[shape.id]!!.jsonObject["cubics"]!!.jsonArray
            assertEquals("${shape.id} cubic count", expected.size, actual.size)
            expected.zip(actual).forEachIndexed { cubicIndex, (expectedCubic, actualCubic) ->
                val values = actualCubic.jsonArray.map { it.jsonPrimitive.double }
                assertEquals("${shape.id} cubic $cubicIndex value count", 8, values.size)
                expectedCubic.zip(values).forEachIndexed { valueIndex, (expectedValue, actualValue) ->
                    assertEquals(
                        "${shape.id} cubic $cubicIndex value $valueIndex",
                        expectedValue,
                        actualValue,
                        1e-6,
                    )
                }
            }
        }
    }

    @Test
    fun fixtureCoversEverySelectedShape() {
        val shapes = fixtureRoot()["shapes"]!!.jsonObject
        assertEquals(LeadingShape.entries.map { it.id }.toSet(), shapes.keys)
        assertEquals(25, shapes.size)
    }

    @Test
    fun fixtureMetricsMeetTheEligibilityGuard() {
        val root = fixtureRoot()
        assertEquals(LeadingShapeGeometry.CONTAINER_DP, root["containerDp"]!!.jsonPrimitive.content.toInt())
        assertEquals(LeadingShapeGeometry.ICON_DP, root["iconDp"]!!.jsonPrimitive.content.toInt())
        root["shapes"]!!.jsonObject.forEach { (id, element) ->
            val shape = element.jsonObject
            val stretch = shape["stretch"]!!.jsonPrimitive.double
            val innerRadius = shape["innerRadius"]!!.jsonPrimitive.double
            assertTrue("$id is stretched in fixture", stretch <= LeadingShapeGeometry.MAX_STRETCH)
            assertTrue(
                "$id cannot hold the icon in fixture",
                innerRadius * 2 * LeadingShapeGeometry.CONTAINER_DP >= LeadingShapeGeometry.MIN_INSCRIBED_DP,
            )
        }
    }

    private fun fixtureRoot(): JsonObject {
        val text = checkNotNull(javaClass.getResourceAsStream("/leading-shapes.json")) {
            "missing shared fixture leading-shapes.json"
        }.bufferedReader(Charsets.UTF_8).use { it.readText() }
        return Json.parseToJsonElement(text).jsonObject
    }

    private fun officialFixture(): JsonObject = buildJsonObject {
        put("note", JsonPrimitive("Generated by LeadingShapeExportTest from official MaterialShapes. Shared by Kotlin and Web; do not edit."))
        put("containerDp", JsonPrimitive(LeadingShapeGeometry.CONTAINER_DP))
        put("iconDp", JsonPrimitive(LeadingShapeGeometry.ICON_DP))
        put("shapes", buildJsonObject {
            LeadingShape.entries.forEach { shape ->
                val metrics = LeadingShapeGeometry.measure(LeadingShapeGeometry.polygonOf(shape))
                put(shape.id, buildJsonObject {
                    put("stretch", JsonPrimitive(round6(metrics.stretch)))
                    put("innerRadius", JsonPrimitive(round6(metrics.innerRadius)))
                    put("cubics", JsonArray(officialCubics(shape).map { cubic ->
                        JsonArray(cubic.map { JsonPrimitive(it) })
                    }))
                })
            }
        })
    }

    private fun officialCubics(shape: LeadingShape): List<List<Double>> =
        LeadingShapeGeometry.polygonOf(shape).cubics.map { cubic ->
            listOf(
                cubic.anchor0X, cubic.anchor0Y,
                cubic.control0X, cubic.control0Y,
                cubic.control1X, cubic.control1Y,
                cubic.anchor1X, cubic.anchor1Y,
            ).map { round6(it.toDouble()) }
        }

    private fun round6(value: Double): Double = round(value * 1_000_000.0) / 1_000_000.0

    private fun fixtureFile(): File {
        var dir: File? = File(System.getProperty("user.dir").orEmpty()).absoluteFile
        while (dir != null) {
            val resources = File(dir, "app/src/test/resources")
            if (resources.isDirectory) return File(resources, "leading-shapes.json")
            dir = dir.parentFile
        }
        error("cannot locate app/src/test/resources")
    }
}
